name: Whiskey Delta
favicon: null
layout_spectrum: 0.9182734228670597
typography_spectrum: 0.4041527262888849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.18460072111338377
  lightness: 0.04483508551493287
  saturation: 0.23596133920364082
  rhythmicContrast: 0.46573498263023794
purpose: []
